version: '3.9'

services:
  stock_portfolio:
    build: ./stock_portfolio_app/
    ports:
      - "5001:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
    driver: local